title: bot di twitch
description: >- # this means to ignore newlines until "baseurl:"
  sito per la dimostrazione di un bot di twitch
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: dave98-dev

# Build settings
remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-feed
